### PR TITLE
cleanup go vendor dir

### PR DESCRIPTION
**Pull request by yussufsh**

### CODE REVIEW

**Comment by yussufsh** [comment]
@travier ptal

**Comment by travier** [comment]
Why is this needed? Which command did you run to clean this? There is no explanation here.

**Comment by yussufsh** [comment]
> Why is this needed? Which command did you run to clean this? There is no explanation here.

This is after running `go mod vendor`. Perhaps this was not cleaned properly in the previous PR #26.

**Comment by yussufsh** [comment]
@travier please help with the review.

**Review by travier — APPROVED** [review]
Sorry, I don't have time for a deeper review. Feel free to merge if it works for you.

**Pull request merged**
