### PR TITLE
ignition_config: add support for http_headers

### LINKED ISSUE #16: Feature Request: Add support for `httpHeaders`
As of configuration specification [version 3.2.0](https://github.com/coreos/ignition/blob/main/docs/configuration-v3_2.md#configuration-specification-v320), there exists an `httpHeaders` field for `merge` and `replace`. We should support this configuration field.

Something like this...

*Desired Input*
```
data "ignition_config" "some_ignition_config" {        
  replace {
    source = "https://api-int.example.com:22623/config/worker"
    httpHeaders = [
      {
        name = "Authorization"
        value = "Bearer token"
      }
    ]
  }
}
```

*Desired Output*
```
{
  "ignition": {
    "config": {
      "replace": [{
        "source": "https://api-int.example.com:22623/config/worker",
        "httpHeaders: [{
          "name": "Authorization",
          "value": "Bearer token"
        }]
      }]
    },
    "version": "3.2.0"
  }
}
```

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #16

### CODE REVIEW

**Comment by travier** [comment]
One thing per PR please. Can you file another PR for the vendor cleanup? Thanks

**Comment by yussufsh** [comment]
> One thing per PR please. Can you file another PR for the vendor cleanup? Thanks

Sure, ptal at #31

**Comment by travier** [comment]
This PR still has the vendor changes

**Comment by yussufsh** [comment]
> This PR still has the vendor changes

I was waiting on the other PR to rebase this branch later.

**Comment by yussufsh** [comment]
> This PR still has the vendor changes

Removed that particular commit.

**Comment by yussufsh** [comment]
@travier please help with the review.

**Review by travier — APPROVED** [review]
Sorry, I don't have time for a deeper review. Feel free to merge if it works for you.

**Pull request merged**
